### ISSUE TITLE
driverentry

### ISSUE THREAD

**Issue by anotherfinemess84** [xtremegamer1/xigmapper#1]
how should it look?  thanks

**Comment by 3r4y** [comment]
mmap.c shouldn't be hard to read

**Comment by xtremegamer1** [comment]
Driver entry can look however you want it to, provided it returns control to the caller. Crucially you cannot use the DriverObject or RegistryPath variables as both will be set to null.

**Comment by xtremegamer1** [comment]
> mmap.c shouldn't be hard to read

Do you mind giving some more nuanced feedback? What don't you like about mmap.c
