### ISSUE TITLE
not loading 

### ISSUE THREAD

**Issue by crabmiau** [xtremegamer1/xigmapper#2]
going into shell and using load "efi driver.efi" just goes forever till i force reboot my pc, nothing else happens

**Comment by xtremegamer1** [comment]
Sorry to hear that. Add me on discord Manilfold#0629 and I will try to help you

**Comment by crabmiau** [comment]
i cant add you, doesnt work

**Comment by crabmiau** [comment]
nevermind i just removed the l and it worked

**Comment by xtremegamer1** [comment]
The issue was crabmiau was compiling for the wrong architecture.
