### ISSUE TITLE
blue screen

### ISSUE THREAD

**Issue by kiRyyy** [xtremegamer1/xigmapper#3]
Hello :)
I'm getting blue screen with message "page fault in nonpaged area" after I run EFI\BOOT\BOOTX64.efi.
I'm using virtual box with w10 64 to test this.

**Comment by xtremegamer1** [comment]
What driver are you trying to map? Also you cannot get a blue screen until you run bootmgfw bc blue screens are from windows not efi

**Comment by kiRyyy** [comment]
An simple driver with print hello world.
My steps are:
fs0:
load "efi driver.efi"
fs1:
EFI\BOOT\BOOTX64.efi

Then I receive the message "Hi from bootkit" and bs

**Comment by kiRyyy** [comment]
ye I think I know where is the problem :) I have to run bootmgfw on windows partition  not BOOTX64 on the pen. anyways how do I find the windows part?

**Comment by kiRyyy** [comment]
well, ignore the previous comment, I already loaded windows from EFI\Microsoft\boot\bootmgfw.efi and works without loading the driver, if I load it gives me the page fault in nonpaged area error. Must be the driver right?
I placed in C: directory, changed the path on hook.c. Idk what is wrong.

**Comment by xtremegamer1** [comment]
What is the path you are using

**Comment by xtremegamer1** [comment]
Also make sure your driver doesn’t crash when loaded with kdmapper

**Comment by kiRyyy** [comment]
Yep, it was crashing with kdmapper, I compiled hello world from kdmapper example and works now. Thanks
