### ISSUE TITLE
Windows 11 ldr_block returning null/not found

### ISSUE THREAD

**Issue by aidenosys** [xtremegamer1/xigmapper#5]
I am looking into getting this EFI Runtime Driver to work on new windows 11 builds (currently testing on winver 23H2), only to find that the Kernel driver that im attempted to load, isn't being started. I have done some debugging on my end, and have found that this line:

 PLOADER_PARAMETER_BLOCK ldr_block = *(PLOADER_PARAMETER_BLOCK*)(*(UINT32*)(scan_result + 0x10) + scan_result + 0x14);

is returning ldr_block as NULL (ldr_block->LoadOrderListHead), i could possibly just be retarted and am probably looking at the fix right before my eyes, but i am lost in trying to get it to work, the problem here is, that ldr_block->LoadOrderListHead is used to get ntoskrnl.exe module in this line:
g_kernel_base = GetModuleFromList(&ldr_block->LoadOrderListHead, L"ntoskrnl.exe")->DllBase; 

which, obviously as ldr_block is returning as NULL, the module base is also null. 

With this, i was wondering it anyone had any useful information as to how i could get this to work on Windows 11, or could point me somewhere i could look into which might help?

Cheers

**Comment by thethanglol** [comment]
the thing is, when i am trying to load my driver using this, it doesn't work, since i am hooking a pointer from one of the sys files, this xigmapper loads your driver even before ntoskrnl.exe, maybe its purpose is different.

**Comment by aidenosys** [comment]
This is an only an issue on the latest windows version - (23H2), i have downgraded to 22H2 in order to see if that had worked, and it did, so i will use this windows version for know and debug it later in hopes to get it working on the latest version!

Cheers, 
Aiden
